### PR TITLE
Upgrade to PHP8.1

### PR DESCRIPTION
**Pull request by ndeblauw**
Hi Nick,

I've taken the liberty to upgrade your script to PHP8.1, so that it works on my new servers. Maybe you want to use my changes to release a new version of your script.

Greetings from Brussels,

Nico

### CODE REVIEW

**Comment by nickdekruijk** [comment]
Any reason why php 8.1 should be the minimum requirement? phpdotenv 5.4 should work with PHP 7.1 or higher

**Comment by ndeblauw** [comment]
To be honest, no. I have PHP 8.1 and therefore just did set it to that requirement - without too much thinking. 

I guess indeed that ^7.0|^8.0 would me more correct - based on what you say.

**Comment by ndeblauw** [comment]
Was going to make a new pull request, but noticed then that my composer change came trough here as well. Sorry for the clumsy git usage, I'm not really a pro in it yet.

**Comment by nickdekruijk** [comment]
> Was going to make a new pull request, but noticed then that my composer change came trough here as well. Sorry for the clumsy git usage, I'm not really a pro in it yet.

Don't worry, this is my first pull request as maintainer so I hope everything went as planned. Projects where I'm using this package still seem to work at least!

**Comment by nickdekruijk** [comment]
And thank you for your contribution!

**Pull request merged**
